### PR TITLE
Revert "point filemaker sites to nginx ingress"

### PR DESCRIPTION
**Pull request by michael-cr41g**
Reverts library-ucsb/iac-dns-route53#79

### CODE REVIEW

**Comment by michael-cr41g** [comment]
Sites weren't being served over a secure connection, there appears to be an issue with ssl certificates being issued.

**Comment by snuffkin007** [comment]
Confirmed that certificates did not seem to have been generated properly for the sites on the NGINX proxy or the K8 pod infrastructure.

**Review by snuffkin007 — APPROVED** [review]
We need to revert the changes, as SSL certificates do not seem to be configured on the NGINX proxy or the pod infrastructure.

**Comment by no-reply** [comment]
it seems like the `cm-acme-http-solver-t25mj` pod has been running for multiple days, which suggests that the certificate hasn't been solved yet for

**Pull request merged**
