### PR TITLE
add cnames for sendgrid domain verification

### PR DESCRIPTION
**Pull request by michael-cr41g**
## [OPS-4725](https://ucsb-atlas.atlassian.net/browse/OPS-4725)

associated with aeon service

image

### CODE REVIEW

**Review by michael-cr41g — COMMENTED** [review]
This appears to be what's needed to fix the s3 backend.

**Comment by michael-cr41g** [comment]
I've removed the `role_arn` value since it was an empty string and we already have a `role_arn` declared for the `aws` provider in `providers.tf`: https://github.com/library-ucsb/iac-dns-route53/blob/aeon-sendgrid/terraform/zones/providers.tf

**Review by snuffkin007 — APPROVED** [review]
Removing the approved condition for executing plan.  Removed the s3 ARN entry all together on the backend.tf file, as there is already an ARN entry in the providers.tf file.  Adding the DNS records for the sendgrid mail domain.

**Comment by snuffkin007** [comment]
Plan has succeeded.

**Pull request merged**
