### PR TITLE
Redirect sites to cloudfront

### PR DESCRIPTION
**Pull request by michael-cr41g**

### CODE REVIEW

**Comment by michael-cr41g** [comment]
Need to get clarification on other sites indexed at misc.library.ucsb.edu.

Currently setup to redirect per request:
https://dhksq0pztv94b.cloudfront.net/universe
https://dhksq0pztv94b.cloudfront.net/untangle

Requested to be shutdown:
http://misc.library.ucsb.edu/ucsel/


Confirm if needed in one way or another:
Truesound
http://misc.library.ucsb.edu/truesound
`redirects to truesound.library.ucsb.edu`

Lobero
https://www.library.ucsb.edu/special-collections/performing-arts/pamss04
`main library page that contains link to http://lobero.library.ucsb.edu/home.php`

ARC
https://www.library.ucsb.edu/special-collections/collections/american-religions-collection
`page on main library website that contains link to http://misc.library.ucsb.edu/arc/home.php, which redirects to http://arc.library.ucsb.edu/home.php`


Currently broken (403):
http://misc.library.ucsb.edu/history/
`should this be working?`

**Comment by michael-cr41g** [comment]
CNAMEs for misc.library.ucsb.edu and legacy.alexandria.ucsb.edu may need to be updated in Win DNS.

**Comment by AndrewEspinoza** [comment]
> CNAMEs for misc.library.ucsb.edu and legacy.alexandria.ucsb.edu may need to be updated in Win DNS.

alexandria.ucsb.edu only exists in WinDNS as a conditional forwarder for the domain to AWS, which may not be needed. There is nothing to change in Windows for a subdomain for alexandria.ucsb.edu.

**Comment by michael-cr41g** [comment]
Per DLD, we only need to redirect untangle and universe paths for `misc`.

These redirects only need to exist for 1 year as a reasonable effort.

**Review by AndrewEspinoza — APPROVED** [review]
I will approve this now for these changes, but it would be worth looking into cleaning up the reverse zones for another change and PR.

**Pull request merged**
